name: Test Connection Dry-Run

on: 
  workflow_dispatch: # This allows you to trigger it manually for testing

jobs:
  test-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Success Message
        run: echo "Docker Hub Login Successful!"

  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            echo "SSH Connection Successful!"
            docker --version
            uptime
